### ISSUE TITLE
Add `web-component` as bower and npm keyword

### ISSUE THREAD

**Issue by zenorocha** [customelements/fetch#24]
> I propose this as there are many elements that have the `web-component` keyword.

> Besides the seed-element also you have [`web-component` keyword](https://github.com/PolymerElements/seed-element/blob/master/bower.json#L9).

Proposed by @abdonrd at https://github.com/customelements/www/issues/519

**Comment by abdonrd** [comment]
I think this is already running, right @zenorocha? :)

**Comment by zenorocha** [comment]
Yep, I've just pushed it ;)

https://github.com/customelements/fetch/commit/f64e8bd9590aa8aecc2491301482d9141b453aa2
https://github.com/customelements/fetch/commit/3c816083d42150e51ebfe6dd94bfeddf25743538

Thanks for reporting @abdonrd ;)
